#!/usr/bin/env bash

MYDIR=$(cd $(dirname $0) && pwd)
$MYDIR/testrunner.js
RC=$?

if [ $RC -ne 0 ]; then
    echo "Exit code=$RC"
    exit $RC
fi

PROJECTROOT=$(cd $MYDIR/..  &&  pwd)
pushd $PROJECTROOT
echo "================Running CLI================="
ls -1 spec/*.js | node cli --consoleOutput=true
RC=$?
popd

echo "Exit code=$RC"
