#!/usr/bin/env bash

MYDIR=$(cd $(dirname $0) && pwd)
$MYDIR/testrunner.js

PROJECTROOT=$(cd $MYDIR/..  &&  pwd)
pushd $PROJECTROOT
echo "================Running CLI================="
ls -1 spec/*.js | node cli
popd
